// Autogenerated by src/import_datamine.js. Do not edit!

import game_0 from "!!raw-loader!../datamine/Game/Umbra/Loot/Armors/Accessories.xml"
import game_1 from "!!raw-loader!../datamine/Game/Umbra/Loot/Armors/Armors_uniques.xml"
import game_2 from "!!raw-loader!../datamine/Game/Umbra/Loot/Armors/Armors.xml"
import game_3 from "!!raw-loader!../datamine/Game/Umbra/Loot/Armors/UniquesAccessories.xml"
import game_4 from "!!raw-loader!../datamine/Game/Umbra/Loot/Weapons/Shields.xml"
import game_5 from "!!raw-loader!../datamine/Game/Umbra/Loot/Weapons/UniqueShields.xml"
import game_6 from "!!raw-loader!../datamine/Game/Umbra/Loot/Weapons/UniqueWeapons.xml"
import game_7 from "!!raw-loader!../datamine/Game/Umbra/Loot/Weapons/UniqueWeaponsMax.xml"
import game_8 from "!!raw-loader!../datamine/Game/Umbra/Loot/Weapons/UniqueWeaponsMaxMax.xml"
import game_9 from "!!raw-loader!../datamine/Game/Umbra/Loot/Weapons/Weapons.xml"
import localization_0 from "!!json-loader!@erosson/xlsx-loader!../datamine/localization/text_ui_Loot.xml"

export default {
  "Game/Umbra/Loot/Armors/Accessories.xml": game_0,
  "Game/Umbra/Loot/Armors/Armors_uniques.xml": game_1,
  "Game/Umbra/Loot/Armors/Armors.xml": game_2,
  "Game/Umbra/Loot/Armors/UniquesAccessories.xml": game_3,
  "Game/Umbra/Loot/Weapons/Shields.xml": game_4,
  "Game/Umbra/Loot/Weapons/UniqueShields.xml": game_5,
  "Game/Umbra/Loot/Weapons/UniqueWeapons.xml": game_6,
  "Game/Umbra/Loot/Weapons/UniqueWeaponsMax.xml": game_7,
  "Game/Umbra/Loot/Weapons/UniqueWeaponsMaxMax.xml": game_8,
  "Game/Umbra/Loot/Weapons/Weapons.xml": game_9,
  "localization/text_ui_Loot.xml": localization_0,
}