name: assets-export
on:
  # schedule:
    # - cron: "5 1 * * *"
  workflow_dispatch:

jobs:
  fetch-and-export:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::add-mask::${{ secrets.STEAMCTL_USER }}"
          echo "::add-mask::${{ secrets.STEAMCTL_PASSWD }}"
          echo "::add-mask::${{ secrets.STEAMCTL_SECRET }}"
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install steamctl pexpect

      - working-directory: ./assets-dl
        env:
          STEAMCTL_USER: ${{ secrets.STEAMCTL_USER }}
          STEAMCTL_PASSWD: ${{ secrets.STEAMCTL_PASSWD }}
          STEAMCTL_SECRET: ${{ secrets.STEAMCTL_SECRET }}
        run: python steamctl-auth.py

      # fetch if and only if there are info.txt differences
      - working-directory: ./assets-dl
        run: yarn fetch

      - working-directory: ./assets-dl
        run: |
          echo 'STEAM_DEPOT_INFO_NEW<<__EOF__' >> $GITHUB_ENV
          cat steam-depot-info.txt >> $GITHUB_ENV
          echo '__EOF__' >> $GITHUB_ENV
          cat $GITHUB_ENV
      - working-directory: ./assets-dl
        run: |
          echo 'STEAM_DEPOT_INFO_DIFF<<__EOF__' >> $GITHUB_ENV
          (diff steam-depot-info-old.txt steam-depot-info.txt || true) >> $GITHUB_ENV
          echo '__EOF__' >> $GITHUB_ENV
          cat $GITHUB_ENV

      # Stop running if there's no info.txt differences
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: yarn install --frozen-lockfile
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: yarn export:install
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: yarn export

      # TODO img deployment; none of the above things actually change the website.
      # Maybe this part should auto-run when `/datamine/**` changes, so it runs only after a PR is merged?
      #- if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
      #  run: yarn build:img
      #- if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
      #  run: yarn deploy:img

      # https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: workflows-assets-export
          commit-message: '[assets-export] Wolcen content updates'
          title: '[ggpk-export] Wolcen content updates'
          body: >
            Looks like Wolcen was patched recently! I've updated WolcenDB for you.

            This PR is auto-generated by the [assets-export robot](https://github.com/erosson/wolcendb/actions?query=workflow%3Aassets-export).
          labels: automated pr
